{
 "title": "Autoscaling dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "service",
    "query": {
     "query": "query_result(label_values(prometheus_http_requests_total, service))"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Utilization %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container_label_io_kubernetes_pod_name=~\"orders-service-.*|payments-service-.*|products-service-.*|rabbitmq\",container_label_io_kubernetes_container_name=~\".+\"\r\n  }[1m])) by (container_label_io_kubernetes_container_name, container_label_io_kubernetes_pod_name)\r\n  /\r\n sum(container_spec_cpu_quota{container_label_io_kubernetes_pod_name=~\"orders-service-.*|payments-service-.*|products-service-.*|rabbitmq\",container_label_io_kubernetes_container_name=~\".+\"} /\r\n container_spec_cpu_period{container_label_io_kubernetes_pod_name=~\"orders-service-.*|payments-service-.*|products-service-.*|rabbitmq\",container_label_io_kubernetes_container_name=~\".+\"}\r\n ) by (container_label_io_kubernetes_container_name, container_label_io_kubernetes_pod_name) * 100",
     "legendFormat": "{{container_label_io_kubernetes_container_name}} "
    }
   ]
  },
  {
   "title": "RAM Utilization %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "# Использование RAM в % от лимита\r\nsum(container_memory_usage_bytes{container_label_io_kubernetes_pod_name=~\"orders-service-.*|payments-service-.*|products-service-.*|rabbitmq\",container_label_io_kubernetes_container_name=~\".+\"}) by (container_label_io_kubernetes_container_name, container_label_io_kubernetes_pod_name) \r\n/ \r\nsum(container_spec_memory_limit_bytes{container_label_io_kubernetes_pod_name=~\"orders-service-.*|payments-service-.*|products-service-.*|rabbitmq\",container_label_io_kubernetes_container_name=~\".+\"} > 0) by (container_label_io_kubernetes_container_name, container_label_io_kubernetes_pod_name) \r\n* 100",
     "legendFormat": "{{container_label_io_kubernetes_container_name}}"
    }
   ]
  },
  {
   "title": "RPS (requests/sec)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (service) (rate(requests_total_by_service[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency (sec)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95,\r\n  sum by (service, route, le) (\r\n    rate(requests_duration_in_seconds_by_service_bucket[1m])\r\n  )\r\n)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}